version: '3.1'

services:
  webstuff:
    container_name: nginx_webstuff
    image: nginx:alpine
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/vhosts:/etc/nginx/conf.d/vhosts"
      - "../source:/var/www/html"
      - log-infra-nginx:/var/log/nginx/
    ports:
      - "8001:80"
    depends_on:
      - php
  php:
    container_name: php_webstuff
    build: php-fpm-debug/                     # Builds the docker container described in `php-fpm-debug/Dockerfile`

    volumes:
      - "../source:/var/www/html"
      - log-app:/var/log/myapp
    environment:
      - IS_LOCAL=YES                          # Create an environment variable 'IS_LOCAL' indicating that this is the local dev environment
      - PORT_FORWARD=8000
#  mysql:
#    container_name: mysql_example
#    image: mysql:5.7
#    command: mysqld --sql_mode=""
#    environment:
#      MYSQL_ROOT_PASSWORD: example
#    ports:
#    - "3306:3306"
#    volumes:
#    - mysql_data:/var/lib/mysql/
#    - "./mysql/data:/docker-entrypoint-initdb.d"
#    - "./mysql/config:/etc/mysql/conf.d"
volumes:
  log-app: ~
  log-infra-nginx: ~
#  mysql_data: ~